version: "3"
services:
  centos7:
    # replace username/repo:tag with your name and image details
    image: centos:7
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 250M
      restart_policy:
        condition: on-failure