version: '3'
services:
  puppet.docker:
    build:
      context: .
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    ports:
      - "80:80"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
