version: '3'
services:
  puppetmaster:
    build: ./puppet.master.vm
    networks:
      puppet:
        aliases:
          - puppet.master.vm
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./puppet.master.vm/r10k:/etc/puppetlabs/r10k
    expose:
      - 8140
  puppetagent:
    build: ./puppet.agent.vm
    networks:
      puppet:
        aliases:
          - puppet.agent.vm

networks:
  puppet:
